name: Publish

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  maven:
    uses: ./.github/workflows/publish-maven.yml
    secrets: inherit

  github:
    uses: ./.github/workflows/publish-github.yml
    secrets: inherit